
link_config: &link_config
    # total length [km] of heralded connection (i.e. sum of fibers on both sides on midpoint station).
    length: 0.0
    # probability that photons are lost when entering connection the connection on either side.
    p_loss_init: 0.2
    # attenuation coefficient [dB/km] of fiber on either side.
    p_loss_length: 0.25
    # speed of light [km/s] in fiber on either side.
    speed_of_light: 200_000
    # dark-count probability per detection
    dark_count_probability: 0
    # probability that the presence of a photon leads to a detection event
    detector_efficiency: 1.0
    # Hong-Ou-Mandel visibility of photons that are being interfered (measure of photon indistinguishability)
    visibility: 1.0
    # determines whether photon-number-resolving detectors are used for the Bell-state measurement
    num_resolving: False

end_node_qdevice_cfg: &end_node_qdevice_cfg
  num_qubits: 2
  # coherence times (same for each qubit)
  T1: 10_000_000_000
  T2: 1_000_000_000
  # gate execution times
  init_time: 10_000
  single_qubit_gate_time: 1_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000
  # noise model
  single_qubit_gate_depolar_prob: 0.01
  two_qubit_gate_depolar_prob: 0.1

repeater_node_qdevice_cfg: &repeater_node_qdevice_cfg
  num_qubits: 2
  # coherence times (same for each qubit)
  T1: 5_000_000_000
  T2: 500_000_000
  # gate execution times
  init_time: 10_000
  single_qubit_gate_time: 1_000
  two_qubit_gate_time: 100_000
  measure_time: 10_000
  # noise model
  single_qubit_gate_depolar_prob: 0
  two_qubit_gate_depolar_prob: 0

processing_nodes:
  - name: h1n0
    qdevice_typ: generic
    qdevice_cfg:
      <<: *end_node_qdevice_cfg
  - name: h1n1
    qdevice_typ: generic
    qdevice_cfg:
      <<: *end_node_qdevice_cfg
  - name: h2n0
    qdevice_typ: generic
    qdevice_cfg:
      <<: *end_node_qdevice_cfg
  - name: h2n1
    qdevice_typ: generic
    qdevice_cfg:
      <<: *end_node_qdevice_cfg


hubs:
  - name: h1
    connections:
      - node: h1n0
        length: 10
      - node: h1n1
        length: 20

    link_typ: heralded-double-click
    link_cfg:
        <<: *link_config

    clink_typ: default
    clink_cfg:
      length: 0

    schedule_typ: fifo
    schedule_cfg:
      switch_time: 1000
      max_multiplexing: 1

  - name: h2
    connections:
      - node: h2n0
        length: 31
      - node: h2n1
        length: 4

    link_typ: heralded-double-click
    link_cfg:
        <<: *link_config

    clink_typ: default
    clink_cfg:
      length: 0

    schedule_typ: fifo
    schedule_cfg:
      switch_time: 1000
      max_multiplexing: 1

repeater_chains:
  - metro_hub1: h1
    metro_hub2: h2

    link_typ: heralded-double-click
    link_cfg:
      <<: *link_config

    clink_typ: default
    clink_cfg:
      length: 0

    repeater_nodes:
      - name: r0
        qdevice_typ: generic
        qdevice_cfg:
          <<: *repeater_node_qdevice_cfg

      - name: r1
        qdevice_typ: generic
        qdevice_cfg:
          <<: *repeater_node_qdevice_cfg

    photonic_interface_typ: depolarise
    photonic_interface_loc: end
    photonic_interface_cfg:
      prob_max_mixed: 0.3
      p_loss: 0.9

    qrep_chain_control_typ: swapASAP
    qrep_chain_control_cfg:
      cutoff_time: null
      parallel_link_generation: true

    lengths:
      - 10
      - 20
      - 10
