processing_nodes:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null

links:
  - node1: Alice
    node2: Bob
    typ: perfect
    cfg:
      state_delay: 2000

clinks:
  - node1: Alice
    node2: Bob
    typ: default
    cfg:
      delay: 400