qdevice_cfg: &qdevice_cfg
  num_qubits: 3
  num_comm_qubits: 1
  T1: 1.e+10
  T2: 1.e+9
  init_time: 1.e+4
  single_qubit_gate_time: 1.e+3
  two_qubit_gate_time: 1.e+5
  measurement_time: 1.e+4
  single_qubit_gate_depolar_prob: 0
  two_qubit_gate_depolar_prob: 0.01

stacks:
  - name: sender
    qdevice_typ: nv
    qdevice_cfg: 
      <<: *qdevice_cfg
    classical_cfg:
      host_qnos_latency: 1e5
  - name: receiver
    qdevice_typ: nv
    qdevice_cfg: 
      <<: *qdevice_cfg
    classical_cfg:
      host_qnos_latency: 1e5
  
link_cfg: &link_cfg
  fidelity: 0.8
  prob_success: 0.01
  t_cycle: 1.e+6

links:
  - stack1: sender
    stack2: receiver
    typ: depolarise_any_bell
    cfg:
      <<: *link_cfg