qdevice: &qdevice
  carbon_T1: 150000000000
  carbon_T2: 1500000000
  carbon_init: 310000
  carbon_init_depolar_prob: 0.05
  carbon_rot_x: 500000
  carbon_rot_y: 500000
  carbon_rot_z: 500000
  carbon_z_rot_depolar_prob: 0.001
  ec_controlled_dir_x: 500000
  ec_controlled_dir_y: 500000
  ec_gate_depolar_prob: 0.008
  electron_T1: 1000000000
  electron_T2: 300000000
  electron_init: 2000
  electron_init_depolar_prob: 0.05
  electron_rot_x: 5
  electron_rot_y: 5
  electron_rot_z: 5
  electron_single_qubit_depolar_prob: 0.0
  host_latency: 100_000_000
  instr_proc_time: 0
  measure: 3700
  prob_error_0: 0.05
  prob_error_1: 0.005
  num_qubits: 2

stacks:
  - name: client
    qdevice_typ: nv
    qdevice_cfg:
      <<: *qdevice
  - name: server
    qdevice_typ: nv
    qdevice_cfg:
      <<: *qdevice

links:
  - stack1: client
    stack2: server
    typ: perfect
    cfg:
      length_A: 0.01
      length_B: 0.01
      full_cycle: 0.1
      cycle_time: 1.0
      alpha: 0.9

clinks:
  - stack1: client
    stack2: server
    typ: default
    cfg:
      delay: 0.5