# Perfect 2 node network, no noise from either computation on the nodes or communication between nodes
processing_nodes:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null

links:
  - node1: Alice
    node2: Bob
    typ: perfect
    cfg:
      dummy: null

clinks:
  - node1: Alice
    node2: Bob
    typ: instant
    cfg:
      dummy: null